services:
  redis:
    image: redis:7
    container_name: superset_cache
    command: ["redis-server", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]

  db:
    image: postgres:15
    container_name: superset_db
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    volumes:
      - db_home:/var/lib/postgresql/data

  superset:
    image: apache/superset:latest
    container_name: superset_app
    ports:
      - "8090:8088"
    depends_on:
      - db
      - redis
    environment:
      SUPERSET_SECRET_KEY: testkey
    command: >
      bash -c "
      pip install psycopg2-binary clickhouse-connect &&
      superset db upgrade &&
      superset fab create-admin \
        --username admin \
        --firstname Admin \
        --lastname User \
        --email admin@local \
        --password admin123 &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "


volumes:
  db_home:
